sonar.projectKey=Devopsawsr_Reddy-K8s
sonar.projectName=Reddy-K8s
sonar.sources=services,packages
sonar.exclusions=services/web/public/**
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12
sonar.qualitygate.wait=true
