BOOKS = [
    {"id": "aws", "name": "AWS book", "price": 22},
    {"id": "terraform", "name": "Terraform book", "price": 19},
    {"id": "kubernetes", "name": "Kubernetes book", "price": 24},
    {"id": "docker", "name": "Docker book", "price": 16},
    {"id": "ansible", "name": "Ansible book", "price": 17},
    {"id": "github", "name": "GitHub Actions", "price": 18},
    {"id": "jenkins", "name": "Jenkins book", "price": 15},
    {"id": "git", "name": "Git book", "price": 14},
    {"id": "python", "name": "Python book", "price": 20},
    {"id": "linux", "name": "Linux book", "price": 16},
    {"id": "prometheus", "name": "Prometheus book", "price": 21},
    {"id": "grafana", "name": "Grafana book", "price": 21},
    {"id": "otel", "name": "OpenTelemetry", "price": 19},
    {"id": "argo", "name": "Argo CD book", "price": 20},
    {"id": "helm", "name": "Helm book", "price": 18},
    {"id": "istio", "name": "Istio book", "price": 20},
    {"id": "opensearch", "name": "OpenSearch book", "price": 19},
    {"id": "elasticsearch", "name": "Elasticsearch", "price": 19},
    {"id": "kibana", "name": "Kibana book", "price": 18},
    {"id": "mlflow", "name": "MLflow book", "price": 21},
    {"id": "tensorflow", "name": "TensorFlow book", "price": 22},
    {"id": "pytorch", "name": "PyTorch book", "price": 22},
    {"id": "mongodb", "name": "MongoDB book", "price": 18},
    {"id": "postgresql", "name": "PostgreSQL book", "price": 18},
    {"id": "redis", "name": "Redis book", "price": 16},
    {"id": "nginx", "name": "Nginx book", "price": 15},
    {"id": "mlops", "name": "MLOps book", "price": 23},
    {"id": "security", "name": "Security book", "price": 22},
    {"id": "exam", "name": "Exam pack", "price": 25},
]
NAMES = {row["id"]: row["name"] for row in BOOKS}
