apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudops-production
  namespace: argocd
spec:
  project: cloudops
  source:
    repoURL: https://github.com/Devopsawsr/Reddy-K8s.git
    targetRevision: main
    path: infra/k8s/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudops-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  # Production: click Sync in Argo CD. No auto-sync.
