apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudops-qa
commonLabels:
  env: qa
resources:
  - namespace.yaml
  - configmap.yaml
  - ../../base
patchesStrategicMerge:
  - gateway-lb.yaml
replicas:
  - name: gateway
    count: 1
  - name: web
    count: 2
images:
  - name: cloudops/gateway
    newName: REPLACE_ECR/cloudops-gateway
    newTag: "0.1-qa"
  - name: cloudops/web
    newName: REPLACE_ECR/cloudops-web
    newTag: "0.1-qa"
  - name: cloudops/auth
    newName: REPLACE_ECR/cloudops-auth
    newTag: "0.1-qa"
  - name: cloudops/catalog
    newName: REPLACE_ECR/cloudops-catalog
    newTag: "0.1-qa"
  - name: cloudops/search
    newName: REPLACE_ECR/cloudops-search
    newTag: "0.1-qa"
  - name: cloudops/inventory
    newName: REPLACE_ECR/cloudops-inventory
    newTag: "0.1-qa"
  - name: cloudops/recommendations
    newName: REPLACE_ECR/cloudops-recommendations
    newTag: "0.1-qa"
  - name: cloudops/cart
    newName: REPLACE_ECR/cloudops-cart
    newTag: "0.1-qa"
  - name: cloudops/orders
    newName: REPLACE_ECR/cloudops-orders
    newTag: "0.1-qa"
  - name: cloudops/learning
    newName: REPLACE_ECR/cloudops-learning
    newTag: "0.1-qa"
  - name: cloudops/labs
    newName: REPLACE_ECR/cloudops-labs
    newTag: "0.1-qa"
  - name: cloudops/community
    newName: REPLACE_ECR/cloudops-community
    newTag: "0.1-qa"
  - name: cloudops/certificates
    newName: REPLACE_ECR/cloudops-certificates
    newTag: "0.1-qa"
  - name: cloudops/leaderboard
    newName: REPLACE_ECR/cloudops-leaderboard
    newTag: "0.1-qa"
