apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudops-dev
commonLabels:
  env: dev
resources:
- namespace.yaml
- configmap.yaml
- pgadmin.yaml
- postgresql-init-configmap.yaml
- postgresql-service.yaml
- postgresql-statefulset.yaml
- database-migration.yaml
- ../../base
patchesStrategicMerge:
- gateway-lb.yaml
replicas:
- count: 1
  name: gateway
- count: 1
  name: web
images:
- name: cloudops/auth
  newName: docker.io/jaganmr49/cloudops-auth
  newTag: c9f22989888f
- name: cloudops/cart
  newName: docker.io/jaganmr49/cloudops-cart
  newTag: c9f22989888f
- name: cloudops/catalog
  newName: docker.io/jaganmr49/cloudops-catalog
  newTag: c9f22989888f
- name: cloudops/certificates
  newName: docker.io/jaganmr49/cloudops-certificates
  newTag: c9f22989888f
- name: cloudops/community
  newName: docker.io/jaganmr49/cloudops-community
  newTag: c9f22989888f
- name: cloudops/gateway
  newName: docker.io/jaganmr49/cloudops-gateway
  newTag: c9f22989888f
- name: cloudops/inventory
  newName: docker.io/jaganmr49/cloudops-inventory
  newTag: c9f22989888f
- name: cloudops/labs
  newName: docker.io/jaganmr49/cloudops-labs
  newTag: c9f22989888f
- name: cloudops/leaderboard
  newName: docker.io/jaganmr49/cloudops-leaderboard
  newTag: c9f22989888f
- name: cloudops/learning
  newName: docker.io/jaganmr49/cloudops-learning
  newTag: c9f22989888f
- name: cloudops/orders
  newName: docker.io/jaganmr49/cloudops-orders
  newTag: c9f22989888f
- name: cloudops/recommendations
  newName: docker.io/jaganmr49/cloudops-recommendations
  newTag: c9f22989888f
- name: cloudops/search
  newName: docker.io/jaganmr49/cloudops-search
  newTag: c9f22989888f
- name: cloudops/web
  newName: docker.io/jaganmr49/cloudops-web
  newTag: c9f22989888f
