apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloudops
  namespace: argocd
spec:
  description: Cloud and DevOps — Dev, QA, Production
  sourceRepos:
    - https://github.com/Devopsawsr/Reddy-K8s.git
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: cloudops-dev
      server: https://kubernetes.default.svc
    - namespace: cloudops-qa
      server: https://kubernetes.default.svc
    - namespace: cloudops-prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: PersistentVolumeClaim
    - group: apps
      kind: Deployment
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: policy
      kind: PodDisruptionBudget
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
