apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudops-root
  namespace: argocd
spec:
  project: cloudops
  source:
    repoURL: https://github.com/Devopsawsr/cloudops-microservices-platform.git
    targetRevision: main
    path: infra/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
